name: Build LaTeX CV
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Rename PDF file
        run: mv main.pdf cv_bingqi_shang.pdf
      - name: Upload PDF file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: cv_bingqi_shang.pdf
      - name: Deploy PDF to branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch --all
          if git show-ref --quiet refs/remotes/origin/pdf; then
            git checkout pdf
          else
            git checkout --orphan pdf
            git rm -rf --ignore-unmatch .
          fi
          mv cv_bingqi_shang.pdf /tmp/
          git reset --hard
          mv /tmp/cv_bingqi_shang.pdf .
          git add cv_bingqi_shang.pdf
          git commit -m "Update CV PDF" || echo "No changes to commit"
          git push origin pdf 